# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'GiantMall' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'YTKNetwork'
  pod 'TMUtils'
  pod 'MJExtension' #字典转模型框架
  pod 'MJRefresh' #tableView上拉下拉刷新组件
  pod 'MBProgressHUD' #loading框架
  pod 'YYText'
  pod 'SDCycleScrollView'

  # Pods for GiantMall

  target 'GiantMallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GiantMallUITests' do
    # Pods for testing
  end

end
